HomeInventory/Controllers/InventoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using HomeInventory.Helper;
using HomeInventory.Models;
using Microsoft.Ajax.Utilities;

namespace HomeInventory.Controllers
{
    public class InventoriesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: HomeItems
        public ActionResult Index(string sortOrder, string sortDir, string searchInput)
        {
            ViewBag.searchInput = searchInput;
            ViewBag.sortOrder = sortOrder;
            ViewBag.sortDir = sortDir;

            if (string.IsNullOrEmpty(sortOrder) && string.IsNullOrEmpty(sortDir) && string.IsNullOrEmpty(searchInput))
            {
                var homeItems1 = db.HomeItems.Include(h => h.PurchaseInfo);
                return View(homeItems1.ToList());
            }

            var homeItems = db.HomeItems.AsQueryable().Include(h => h.PurchaseInfo);
            if (!string.IsNullOrEmpty(searchInput))
            {
                homeItems = homeItems.Where(h => h.Description.Contains(searchInput));
            }

            if (sortOrder != null)
            {
                switch (sortOrder.ToLower())
                {
                    case "description":
                        if (sortDir.ToLower() == "desc")
                        {
                            homeItems = homeItems.OrderByDescending(h => h.Description);
                        }
                        else
                        {
                            homeItems = homeItems.OrderBy(h => h.Description);
                        }
                        break;
                    case "location":
                        if (sortDir.ToLower() == "desc")
                        {
                            homeItems = homeItems.OrderByDescending(h => h.LocationId);
                        }
                        else
                        {
                            homeItems = homeItems.OrderBy(h => h.LocationId);
                        }
                        break;
                    case "model":
                        if (sortDir.ToLower() == "desc")
                        {
                            homeItems = homeItems.OrderByDescending(h => h.Model);
                        }
                        else
                        {
                            homeItems = homeItems.OrderBy(h => h.Model);
                        }
                        break;
                    case "serial number":
                        if (sortDir.ToLower() == "desc")
                        {
                            homeItems = homeItems.OrderByDescending(h => h.SerialNumber);
                        }
                        else
                        {
                            homeItems = homeItems.OrderBy(h => h.SerialNumber);
                        }
                        break;
                    default:
                        break;
                }
            }
            return View(homeItems.ToList());
        }

        // GET: HomeItems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var homeItems = db.HomeItems.Include(c => c.PurchaseInfo);
            HomeItem homeItem = homeItems.FirstOrDefault(h => h.HomeItemId == id);
            if (homeItem == null)
            {
                return HttpNotFound();
            }
            return View(homeItem);
        }

        // GET: HomeItems/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HomeItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "HomeItemId,Description,Model,SerialNumber,LocationId,PurchaseInfoId,PurchaseInfo.When,PurchaseInfo.Where,PurchaseInfo.Warranty,PurchaseInfo.Price,Photo,PhotoDB,PurchaseInfo")] HomeItemViewModel homeItemVM)
        {
            if (ModelState.IsValid)
            {
                Mapper.CreateMap<HomeItemViewModel, HomeItem>().ForMember(h => h.Photo, opt => opt.Ignore());
                var homeItem = Mapper.Map<HomeItem>(homeItemVM);
                if (homeItemVM.Photo != null)
                {
                    homeItem.Photo = ImageConverter.ByteArrayFromPostedFile(homeItemVM.Photo);
                }

                db.PurchaseInfos.Add(homeItem.PurchaseInfo);
                db.HomeItems.Add(homeItem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(homeItemVM);
        }

        // GET: HomeItems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var homeItems = db.HomeItems.Include(c => c.PurchaseInfo);
            HomeItem homeItem = homeItems.FirstOrDefault(h => h.HomeItemId == id);
            if (homeItem == null)
            {
                return HttpNotFound();
            }
            Mapper.CreateMap<HomeItem, HomeItemViewModel>().ForMember(h => h.Photo, opt => opt.Ignore());
            HomeItemViewModel hvm = Mapper.Map<HomeItemViewModel>(homeItem);
            hvm.PhotoDB = homeItem.Photo;
            return View(hvm);
        }

        // POST: HomeItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "HomeItemId,Description,Model,SerialNumber,LocationId,PurchaseInfoId,PurchaseInfo.When,PurchaseInfo.Where,PurchaseInfo.Warranty,PurchaseInfo.Price,Photo,PhotoDB,PurchaseInfo")] HomeItemViewModel homeItemVM)
        {
            if (ModelState.IsValid)
            {
                Mapper.CreateMap<HomeItemViewModel, HomeItem>().ForMember(f => f.Photo, opt => opt.Ignore());
                var homeItem = Mapper.Map<HomeItem>(homeItemVM);
                homeItem.Photo = homeItemVM.Photo != null ? ImageConverter.ByteArrayFromPostedFile(homeItemVM.Photo) : homeItemVM.PhotoDB;
                db.PurchaseInfos.AddOrUpdate(homeItem.PurchaseInfo);
                db.HomeItems.AddOrUpdate(homeItem);
                //db.Entry(homeItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(homeItemVM);
        }

        // GET: HomeItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var homeItems = db.HomeItems.Include(h=>h.PurchaseInfo);
            HomeItem homeItem = homeItems.FirstOrDefault(h => h.HomeItemId == id);
            if (homeItem == null)
            {
                return HttpNotFound();
            }
            return View(homeItem);
        }

        // POST: HomeItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var homeItems = db.HomeItems.Include(h => h.PurchaseInfo);
            HomeItem homeItem = homeItems.FirstOrDefault(h => h.HomeItemId == id);
            db.PurchaseInfos.Remove(homeItem.PurchaseInfo);
            db.HomeItems.Remove(homeItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HomeInventory/Views/Inventories/Create.cshtml
@using HomeInventory.Helper
@using HomeInventory.Models
@model HomeInventory.Models.HomeItemViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Inventories", FormMethod.Post, new { @enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Inventory</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LocationId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.LocationId, EnumHelper.GetSelectList(typeof(Location)), "Select a location", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.LocationId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SerialNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SerialNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SerialNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PurchaseInfo.When, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PurchaseInfo.When, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PurchaseInfo.When, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PurchaseInfo.Where, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PurchaseInfo.Where, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PurchaseInfo.Where, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PurchaseInfo.Warranty, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PurchaseInfo.Warranty, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PurchaseInfo.Warranty, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PurchaseInfo.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PurchaseInfo.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PurchaseInfo.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="Photo" accept="image/x-png,image/gif,image/jpeg" />
            @if (Model != null && Model.PhotoDB != null)
            {
                @Html.GetThumbnail(Model.PhotoDB, 150, 150)
            }
            @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HomeInventory/Views/Inventories/Delete.cshtml
@using HomeInventory.Helper
@model HomeInventory.Models.HomeItem

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Inventory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LocationId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocationId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SerialNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SerialNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchaseInfo.When)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchaseInfo.When)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchaseInfo.Where)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchaseInfo.Where)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchaseInfo.Warranty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchaseInfo.Warranty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchaseInfo.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchaseInfo.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @if (Model.Photo != null)
            {
                @Html.GetThumbnail(Model.Photo)
            }
        </dd>

    </dl>

    @using (Html.BeginForm("Delete", "Inventories", FormMethod.Post, new { @enctype = "multipart/form-data" })) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HomeInventory/Views/Inventories/Details.cshtml
@using HomeInventory.Helper
@model HomeInventory.Models.HomeItem

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Inventory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LocationId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocationId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SerialNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SerialNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchaseInfo.When)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchaseInfo.When)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchaseInfo.Where)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchaseInfo.Where)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchaseInfo.Warranty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchaseInfo.Warranty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchaseInfo.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchaseInfo.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @if (Model.Photo != null)
            {
                @Html.GetThumbnail(Model.Photo)
            }
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.HomeItemId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HomeInventory/Views/Inventories/Edit.cshtml
@using HomeInventory.Helper
@using HomeInventory.Models
@model HomeInventory.Models.HomeItemViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Inventories", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Inventory</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.HomeItemId)
    @Html.HiddenFor(model => model.PurchaseInfoId)
    @Html.HiddenFor(model => model.PurchaseInfo.PurchaseInfoId)

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LocationId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.LocationId, EnumHelper.GetSelectList(typeof(Location)), "Select a location", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.LocationId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SerialNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SerialNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SerialNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PurchaseInfo.When, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PurchaseInfo.When, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PurchaseInfo.When, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PurchaseInfo.Where, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PurchaseInfo.Where, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PurchaseInfo.Where, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PurchaseInfo.Warranty, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PurchaseInfo.Warranty, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PurchaseInfo.Warranty, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PurchaseInfo.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PurchaseInfo.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PurchaseInfo.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="Photo" accept="image/x-png,image/gif,image/jpeg" />
            @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.HiddenFor(model => model.PhotoDB)
        <div class="col-md-2">
        </div>
        <div class="col-md-10">
            @if (Model != null && Model.PhotoDB != null)
            {
                @Html.GetThumbnail(Model.PhotoDB, 150, 150)
            }
            @Html.ValidationMessageFor(model => model.PhotoDB, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HomeInventory/Views/Inventories/Index.cshtml
@using HomeInventory.Helper
@model IEnumerable<HomeInventory.Models.HomeItem>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<form asp-controller="Inventories" asp-action="Index" method="post">
    <p>
            <input type="text" name="searchInput" style="border-radius: 5px" placeholder="Description" value="@ViewBag.searchInput"/>
            <input type="submit" value="Search" />
    </p>
</form>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Photo)
        </th>
        <th>
            @Html.ActionLink("Description", "Index", new {sortOrder = "Description", sortDir = string.IsNullOrEmpty(ViewBag.sortDir) ? "asc" : (ViewBag.sortDir == "asc" ? "desc" : "asc"), searchInput = ViewBag.searchInput })
            @Html.GetArrow((string)ViewBag.sortOrder, "Description", (string)ViewBag.sortDir)
        </th>
        <th>
            @Html.ActionLink("Location", "Index", new { sortOrder = "Location", sortDir = string.IsNullOrEmpty(ViewBag.sortDir) ? "asc" : (ViewBag.sortDir == "asc" ? "desc" : "asc"), searchInput = ViewBag.searchInput })
            @Html.GetArrow((string)ViewBag.sortOrder, "Location", (string)ViewBag.sortDir)
        </th>
        <th>
            @Html.ActionLink("Model", "Index", new { sortOrder = "Model", sortDir = string.IsNullOrEmpty(ViewBag.sortDir) ? "asc" : (ViewBag.sortDir == "asc" ? "desc" : "asc"), searchInput = ViewBag.searchInput })
            @Html.GetArrow((string)ViewBag.sortOrder, "Model", (string)ViewBag.sortDir)
        </th>
        <th>
            @Html.ActionLink("Serial Number", "Index", new { sortOrder = "Serial Number", sortDir = string.IsNullOrEmpty(ViewBag.sortDir) ? "asc" : (ViewBag.sortDir == "asc" ? "desc" : "asc"), searchInput = ViewBag.searchInput })
            @Html.GetArrow((string)ViewBag.sortOrder, "Serial Number", (string)ViewBag.sortDir)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PurchaseInfoId)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @if (item.Photo != null)
                {
                    @Html.GetThumbnail(item.Photo, 100, 100)
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LocationId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SerialNumber)
            </td>
            <td>
                @Html.HiddenFor(modelItem => item.PurchaseInfoId)
                @Html.Partial("IndexPartial", item.PurchaseInfo)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.HomeItemId }) |
                @Html.ActionLink("Details", "Details", new { id = item.HomeItemId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.HomeItemId })
            </td>
        </tr>
    }
</table>